# Generated by Django 4.2.12 on 2024-05-09 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_bibliographicreference_remove_project_portada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bibliographic_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.bibliographicreference'),
        ),
    ]
