# Generated by Django 4.2.12 on 2024-05-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_project_bibliographic_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bibliographic_reference',
        ),
    ]
