# Generated by Django 4.2.12 on 2024-05-10 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_remove_project_bibliographic_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliographicreference',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biblio', to='proyectos.project'),
        ),
    ]
