# Generated by Django 4.2.12 on 2024-05-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_workplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cv',
            field=models.FileField(blank=True, help_text='En calidad de coordinador/a o autor/a del proyecto, que acredite experiencia en el campo del conocimiento pertinente, así como experiencia en temas editoriales, de publicación, coordinación y/o de curaduría de proyectos culturales o académicos según corresponda, de al menos 2 años.', null=True, upload_to='curriculms/', verbose_name='Perfil del postulante'),
        ),
        migrations.AddField(
            model_name='project',
            name='plan',
            field=models.TextField(blank=True, help_text='Detalle de manera clara y sucinta.', null=True, verbose_name='Describa el plan de uso de incentivo'),
        ),
    ]
