# Generated by Django 4.2.12 on 2024-05-22 08:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dictamen',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Si el proceso se encuentrta en Aprobado y calificado, Escribir en el re-cuadro el dicatmen final de jurado.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='recomend',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Si el proceso se encuentrta en subsanamiento, Escribir en el re-cuadro, las recomendaciones.', null=True),
        ),
    ]
