# Generated by Django 4.2.12 on 2024-05-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_author_first_name_author_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nombre completo de Autor'),
        ),
    ]
