# Generated by Django 4.2.12 on 2024-05-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_remove_author_first_name_remove_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_contents_project', to='proyectos.author'),
        ),
    ]
