# Generated by Django 4.2.11 on 2024-04-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='georeferenciacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Georreferenciación'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='perfil_redes_sociales',
            field=models.URLField(blank=True, null=True, verbose_name='Perfil de Redes Sociales'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
