# Generated by Django 4.2.11 on 2024-04-17 21:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_contacts_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_de_despedida', ckeditor.fields.RichTextField(default=False, verbose_name='Términos y Condiciones de Uso')),
            ],
        ),
    ]
