# Generated by Django 4.2.12 on 2024-05-09 05:11

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_contacts_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='perfil_redes_sociales',
            field=models.URLField(blank=True, help_text='Pegue aquí la dirección Url de superfil de usuario en redes sociales.', null=True, verbose_name='Perfil de Redes Sociales'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='telefono_contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
    ]
