# Generated by Django 4.2.11 on 2024-04-11 04:34

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_activity_date_of_birth_remove_activity_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='pais_residencia',
            field=django_countries.fields.CountryField(default='Ecuador', max_length=2, verbose_name='País de Residencia'),
        ),
    ]
