# Generated by Django 4.2.11 on 2024-04-13 17:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_contacts_pais_residencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('informacion_basica', ckeditor.fields.RichTextField()),
                ('bloque_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link_soporte_tecnico', models.URLField()),
            ],
        ),
    ]
