# Generated by Django 4.2.12 on 2024-05-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_activityprivacypolicy_activitytermsofuse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_group',
        ),
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.CharField(blank=True, choices=[('POSTULANTE', 'Postular proyectos a convocatorias'), ('PROPONIENTE', 'Proponer actividades culturales en espacios públicos')], max_length=120, null=True, verbose_name='¿Que actividad cultural desea realizar en nuestra plataforma?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Agregar Foto de Perfil'),
        ),
    ]
