# Generated by Django 4.2.12 on 2024-05-21 02:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_profile_user_group_profile_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='lugar_residencia',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='pais_residencias',
            field=django_countries.fields.CountryField(blank=True, help_text='Elija el país en el que usted reside', max_length=150, multiple=True, verbose_name='País de Residencia'),
        ),
    ]
