# Generated by Django 4.2.6 on 2024-03-08 22:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual_creacion_convocatoria_fomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', ckeditor.fields.RichTextField(verbose_name='Introducción')),
                ('paso1', ckeditor.fields.RichTextField(verbose_name='caracteristicas del app de inscripciones')),
                ('paso2', ckeditor.fields.RichTextField(verbose_name='paso1- informacion de usuario ')),
                ('paso3', ckeditor.fields.RichTextField(verbose_name='paso2 -informacion de contacto')),
                ('paso4', ckeditor.fields.RichTextField(null=True, verbose_name='paso3-informacion de legal')),
                ('paso5', ckeditor.fields.RichTextField(null=True, verbose_name='paso4-informacion de legal-natural')),
                ('paso6', ckeditor.fields.RichTextField(null=True, verbose_name='paso5-informacion de legal-juridico')),
                ('paso7', ckeditor.fields.RichTextField(null=True, verbose_name='paso6-informacion de actividades')),
                ('paso8', ckeditor.fields.RichTextField(null=True, verbose_name='paso7-informacion de actividades')),
                ('paso9', ckeditor.fields.RichTextField(null=True, verbose_name='paso7-declaratoria')),
            ],
            options={
                'verbose_name': 'Manual crear convocatoria línea de fomento editorial',
                'verbose_name_plural': 'Manual crear convocatoria línea de fomento editorial',
            },
        ),
        migrations.CreateModel(
            name='Manual_editar_configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', ckeditor.fields.RichTextField(verbose_name='Introducción')),
                ('paso1', ckeditor.fields.RichTextField(verbose_name='caracteristicas del app de inscripciones')),
                ('paso2', ckeditor.fields.RichTextField(verbose_name='paso1- informacion de usuario ')),
                ('paso3', ckeditor.fields.RichTextField(verbose_name='paso2 -informacion de contacto')),
                ('paso4', ckeditor.fields.RichTextField(null=True, verbose_name='paso3-informacion de legal')),
                ('paso5', ckeditor.fields.RichTextField(null=True, verbose_name='paso4-informacion de legal-natural')),
                ('paso6', ckeditor.fields.RichTextField(null=True, verbose_name='paso5-informacion de legal-juridico')),
                ('paso7', ckeditor.fields.RichTextField(null=True, verbose_name='paso6-informacion de actividades')),
                ('paso8', ckeditor.fields.RichTextField(null=True, verbose_name='paso7-informacion de actividades')),
                ('paso9', ckeditor.fields.RichTextField(null=True, verbose_name='paso7-declaratoria')),
            ],
            options={
                'verbose_name': 'Manual configuracion',
                'verbose_name_plural': 'Manual configuracion',
            },
        ),
        migrations.CreateModel(
            name='Manual_editar_convocatoria_fomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', ckeditor.fields.RichTextField(verbose_name='Introducción')),
                ('paso1', ckeditor.fields.RichTextField(verbose_name='caracteristicas del app de inscripciones')),
                ('paso2', ckeditor.fields.RichTextField(verbose_name='paso1- informacion de usuario ')),
                ('paso3', ckeditor.fields.RichTextField(verbose_name='paso2 -informacion de contacto')),
                ('paso4', ckeditor.fields.RichTextField(null=True, verbose_name='paso3-informacion de legal')),
                ('paso5', ckeditor.fields.RichTextField(null=True, verbose_name='paso4-informacion de legal-natural')),
                ('paso6', ckeditor.fields.RichTextField(null=True, verbose_name='paso5-informacion de legal-juridico')),
                ('paso7', ckeditor.fields.RichTextField(null=True, verbose_name='paso6-informacion de actividades')),
                ('paso8', ckeditor.fields.RichTextField(null=True, verbose_name='paso7-informacion de actividades')),
                ('paso9', ckeditor.fields.RichTextField(null=True, verbose_name='paso7-declaratoria')),
            ],
            options={
                'verbose_name': 'Manual editar convocatoria línea de fomento editorialn',
                'verbose_name_plural': 'Manual editar convocatoria línea de fomento editorialn',
            },
        ),
        migrations.CreateModel(
            name='Manual_lineasfomento_editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', ckeditor.fields.RichTextField(verbose_name='Introducción')),
                ('paso1', ckeditor.fields.RichTextField(verbose_name='caracteristicas del app de inscripciones')),
                ('paso2', ckeditor.fields.RichTextField(verbose_name='paso1- informacion de usuario ')),
                ('paso3', ckeditor.fields.RichTextField(verbose_name='paso2 -informacion de contacto')),
                ('paso4', ckeditor.fields.RichTextField(null=True, verbose_name='paso3-informacion de legal')),
                ('paso5', ckeditor.fields.RichTextField(null=True, verbose_name='paso4-informacion de legal-natural')),
                ('paso6', ckeditor.fields.RichTextField(null=True, verbose_name='paso5-informacion de legal-juridico')),
                ('paso7', ckeditor.fields.RichTextField(null=True, verbose_name='paso6-informacion de actividades')),
                ('paso8', ckeditor.fields.RichTextField(null=True, verbose_name='paso7-informacion de actividades')),
                ('paso9', ckeditor.fields.RichTextField(null=True, verbose_name='paso7-declaratoria')),
            ],
            options={
                'verbose_name': 'Manual de línea de fomento editorial',
                'verbose_name_plural': 'Manuales de línea de fomento editorial',
            },
        ),
    ]
