# Generated by Django 4.2.6 on 2024-03-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='activity_jury',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ACTIVIDAD PRINCIPAL A LA QUE SE DEDICA LA EMPRESA'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='autoidenty_etnica',
            field=models.CharField(blank=True, choices=[('Indígena', 'Indígena'), ('Afroecuatoriano', 'Afroecuatoriano'), ('Montubio', 'Montubio'), ('Mestizo/a', 'Mestizo/a'), ('Blanco/a', 'Blanco/a'), ('Otro/a', 'Otro/a')], max_length=200, null=True, verbose_name='Autoidentificación Etnica del representante legal'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='dactilar',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Código Dactilar del representante legal'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento del representante legal'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No binario', 'Montubio'), ('Género fluido', 'Género fluido'), ('Bigénero', 'Bigénero'), ('Transexual', 'Transexual'), ('Andrógino', 'Andrógino')], max_length=200, null=True, verbose_name='Autoidentificación Género del representante legal'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='lucro_jury',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=200, null=True, verbose_name='¿ La personería jurídica tiene fines de lucro ?a'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Nacionalidad del representante legal'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='numero_cedula',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de cedula del representante legal'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='tipo_jury',
            field=models.CharField(blank=True, choices=[('ASOCIACIONES SIN ÁNIMO DE LUCRO', 'ASOCIACIONES SIN ÁNIMO DE LUCRO'), ('ASOCIACIÓN DE CUENTAS DE PARTICIPACIÓN', 'ASOCIACIÓN DE CUENTAS DE PARTICIPACIÓN'), ('COMPAÑÍA LIMITADA CÍA. LTDA.', 'COMPAÑÍA LIMITADA CÍA. LTDA.'), ('EMPRESARIO INDIVIDUAL', 'EMPRESARIO INDIVIDUAL'), ('SOCIEDAD ANÓNIMA S.A.', 'SOCIEDAD ANÓNIMA S.A.'), ('SOCIEDAD DE ACCIONES SIMPLIFICADA S.A.S', 'SOCIEDAD DE ACCIONES SIMPLIFICADA S.A.S'), ('SOCIEDAD COLECTIVA', 'SOCIEDAD COLECTIVA.'), ('SOCIEDAD COMANDATARIA', 'SOCIEDAD COMANDATARIA'), ('SOCIEDAD COOPERATIVA', 'SOCIEDAD COOPERATIVA'), ('SOCIEDAD LIMITADA S.L.', 'SOCIEDAD LIMITADA S.L.')], max_length=200, null=True, verbose_name='Tipo de personería jurídica'),
        ),
    ]
