# Generated by Django 4.2.6 on 2024-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_profile',
            name='canton1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact_profile',
            name='parroquia1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
