# Generated by Django 4.2.6 on 2024-03-05 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_profile_done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tech', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Tecnico a cargo')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name=' Telefono de contacto del Tecnico a cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico del Tecnico a cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Información de tecnico',
                'verbose_name_plural': 'Información de tecnico',
            },
        ),
        migrations.RemoveField(
            model_name='parroquia',
            name='canton',
        ),
        migrations.DeleteModel(
            name='Canton',
        ),
        migrations.DeleteModel(
            name='Parroquia',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
