# Generated by Django 4.2.6 on 2024-03-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantes_lineas_fomentos',
            name='agregar_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Agregar nombre de participante'),
        ),
    ]
