# Generated by Django 4.2.6 on 2024-02-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='natural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('Azuay', 'Azuay'), ('Bolívar', 'Bolívar'), ('Cañar', 'Cañar'), ('Carchi', 'Carchi'), ('Chimborazo', 'Chimborazo'), ('Cotopaxi', 'Cotopaxi'), ('Esmeraldas', 'Esmeraldas'), ('Galápagos', 'Galápagos'), ('Guayas', 'Guayas'), ('Imbabura', 'Imbabura'), ('Loja', 'Loja'), ('Los Ríos', 'Los Ríos'), ('Manabí', 'Manabí'), ('Morona Santiago', 'Morona Santiago'), ('Napo', 'Napo'), ('Orellana', 'Orellana'), ('Pastaza', 'Pastaza'), ('Pichincha', 'Pichincha'), ('Santa Elena', 'Santa Elena'), ('Santo Domingo de los Tsáchilas', 'Santo Domingo de los Tsáchilas'), ('Sucumbíos', 'Sucumbíos'), ('Tungurahua', 'Tungurahua'), ('Zamora Chinchipe', 'Zamora Chinchipe')], max_length=200, null=True)),
                ('canton1', models.CharField(choices=[('Cuenca', 'Cuenca'), ('Chordeleg', 'Chordeleg'), ('El Pan', 'El Pan'), ('Girón', 'Girón'), ('Guachapala', 'Guachapala'), ('Gualaceo', 'Gualaceo'), ('Nabón', 'Nabón'), ('Oña', 'Oña'), ('Paute', 'Paute'), ('Pucará', 'Pucará'), ('San Fernando', 'San Fernando'), ('Santa Isabel', 'Santa Isabel'), ('Sevilla de Oro', 'Sevilla de Oro'), ('Sígsig', 'Sígsig'), ('Camilo Ponce Enríquez', 'Camilo Ponce Enríquez')], max_length=200, null=True)),
                ('canton2', models.CharField(choices=[('Guaranda', 'Guaranda'), ('Chillanes', 'Chillanes'), ('Chimbo', 'Chimbo'), ('Echeandía', 'Echeandía'), ('San Miguel', 'San Miguel'), ('Caluma', 'Caluma')], max_length=200, null=True)),
                ('canton3', models.CharField(choices=[('Azogues', 'Azogues'), ('Biblián', 'Biblián'), ('Cañar', 'Cañar'), ('La Troncal', 'La Troncal'), ('Déleg', 'Déleg'), ('El Tambo', 'El Tambo'), ('Suscal', 'Suscal')], max_length=200, null=True)),
                ('canton4', models.CharField(choices=[('Tulcán', (('González Suárez', 'González Suárez'), ('Tufiño', 'Tufiño'))), ('Bolívar', (('Bolívar', 'Bolívar'), ('García Moreno', 'García Moreno'))), ('Espejo', (('El Ángel', 'El Ángel'), ('El Goaltal', 'El Goaltal')))], max_length=200, null=True)),
                ('canton5', models.CharField(choices=[('Riobamba', 'Riobamba'), ('Alausí', 'Alausí'), ('Chambo', 'Chambo'), ('Chunchi', 'Chunchi'), ('Colta', 'Colta'), ('Cumandá', 'Cumandá'), ('Guamote', 'Guamote'), ('Guano', 'Guano'), ('Pallatanga', 'Pallatanga'), ('Penipe', 'Penipe')], max_length=200, null=True)),
                ('canton6', models.CharField(choices=[('Latacunga', 'Latacunga'), ('La Maná', 'La Maná'), ('Pangua', 'Pangua'), ('Pujilí', 'Pujilí'), ('Salcedo', 'Salcedo'), ('Saquisilí', 'Saquisilí'), ('Sigchos', 'Sigchos')], max_length=200, null=True)),
                ('canton7', models.CharField(choices=[('Esmeraldas', 'Esmeraldas'), ('Atacames', 'Atacames'), ('Eloy Alfaro', 'Eloy Alfaro'), ('Muisne', 'Muisne'), ('Quinindé', 'Quinindé'), ('San Lorenzo', 'San Lorenzo')], max_length=200, null=True)),
                ('canton8', models.CharField(choices=[('San Cristóbal', 'San Cristóbal'), ('Santa Cruz', 'Santa Cruz'), ('Isabela', 'Isabela')], max_length=200, null=True)),
                ('canton9', models.CharField(choices=[('Ibarra', 'Ibarra'), ('Antonio Ante', 'Antonio Ante'), ('Cotacachi', 'Cotacachi'), ('Otavalo', 'Otavalo'), ('Pimampiro', 'Pimampiro'), ('San Miguel de Urcuquí', 'San Miguel de Urcuquí')], max_length=200, null=True)),
                ('canton10', models.CharField(choices=[('Loja', 'Loja'), ('Calvas', 'Calvas'), ('Catamayo', 'Catamayo'), ('Celica', 'Celica'), ('Chaguarpamba', 'Chaguarpamba'), ('Espíndola', 'Espíndola'), ('Gonzanamá', 'Gonzanamá'), ('Macará', 'Macará'), ('Paltas', 'Paltas'), ('Pindal', 'Pindal'), ('Puyango', 'Puyango'), ('Quilanga', 'Quilanga'), ('Saraguro', 'Saraguro'), ('Sozoranga', 'Sozoranga'), ('Zapotillo', 'Zapotillo')], max_length=200, null=True)),
                ('canton11', models.CharField(choices=[('Babahoyo', 'Babahoyo'), ('Baba', 'Baba'), ('Montalvo', 'Montalvo'), ('Pueblo Viejo', 'Pueblo Viejo'), ('Quevedo', 'Quevedo'), ('Urdaneta', 'Urdaneta'), ('Ventanas', 'Ventanas'), ('Vinces', 'Vinces')], max_length=200, null=True)),
                ('canton12', models.CharField(choices=[('Portoviejo', 'Portoviejo'), ('Chone', 'Chone'), ('El Carmen', 'El Carmen'), ('Jipijapa', 'Jipijapa'), ('Manta', 'Manta'), ('Montecristi', 'Montecristi'), ('Santa Ana', 'Santa Ana'), ('Sucre', 'Sucre'), ('Tosagua', 'Tosagua'), ('24 de Mayo', '24 de Mayo'), ('Bolívar', 'Bolívar'), ('Junín', 'Junín'), ('Paján', 'Paján'), ('Jaramijó', 'Jaramijó'), ('Olmedo', 'Olmedo'), ('Pedernales', 'Pedernales'), ('Puerto López', 'Puerto López'), ('San Vicente', 'San Vicente')], max_length=200, null=True)),
                ('canton13', models.CharField(choices=[('Morona', 'Morona'), ('Gualaquiza', 'Gualaquiza'), ('Limoncocha', 'Limoncocha'), ('Palora', 'Palora'), ('Santiago', 'Santiago'), ('Sucúa', 'Sucúa'), ('Huamboya', 'Huamboya')], max_length=200, null=True)),
                ('canton14', models.CharField(choices=[('Tena', 'Tena'), ('Archidona', 'Archidona'), ('El Chaco', 'El Chaco'), ('Quijos', 'Quijos')], max_length=200, null=True)),
                ('canton15', models.CharField(choices=[('Orellana', 'Orellana'), ('Aguarico', 'Aguarico'), ('La Joya de los Sachas', 'La Joya de los Sachas')], max_length=200, null=True)),
                ('canton16', models.CharField(choices=[('Pastaza', 'Pastaza'), ('Mera', 'Mera'), ('Santa Clara', 'Santa Clara'), ('Arajuno', 'Arajuno')], max_length=200, null=True)),
                ('canton17', models.CharField(choices=[('Quito', 'Quito'), ('Cayambe', 'Cayambe'), ('Mejía', 'Mejía'), ('Pedro Moncayo', 'Pedro Moncayo'), ('Pedro Vicente Maldonado', 'Pedro Vicente Maldonado'), ('Puerto Quito', 'Puerto Quito'), ('Rumiñahui', 'Rumiñahui'), ('San Miguel de Los Bancos', 'San Miguel de Los Bancos')], max_length=200, null=True)),
                ('canton18', models.CharField(choices=[('Santa Elena', 'Santa Elena'), ('La Libertad', 'La Libertad'), ('Salinas', 'Salinas')], max_length=200, null=True)),
                ('canton19', models.CharField(choices=[('Santo Domingo', 'Santo Domingo'), ('La Concordia', 'La Concordia')], max_length=200, null=True)),
                ('canton20', models.CharField(choices=[('Lago Agrio', 'Lago Agrio'), ('Gonzalo Pizarro', 'Gonzalo Pizarro'), ('Putumayo', 'Putumayo'), ('Shushufindi', 'Shushufindi')], max_length=200, null=True)),
                ('canton21', models.CharField(choices=[('Ambato', 'Ambato'), ('Baños de Agua Santa', 'Baños de Agua Santa'), ('Cevallos', 'Cevallos'), ('Mocha', 'Mocha'), ('Patate', 'Patate'), ('Quero', 'Quero'), ('Pelileo', 'Pelileo'), ('Pillaro', 'Pillaro'), ('Tisaleo', 'Tisaleo')], max_length=200, null=True)),
                ('canton22', models.CharField(choices=[('Zamora', 'Zamora'), ('Chinchipe', 'Chinchipe'), ('Nangaritza', 'Nangaritza'), ('Yacuambi', 'Yacuambi'), ('Yantzaza', 'Yantzaza'), ('El Pangui', 'El Pangui'), ('Centinela del Cóndor', 'Centinela del Cóndor'), ('Palanda', 'Palanda'), ('Paquisha', 'Paquisha')], max_length=200, null=True)),
                ('parroquia1', models.CharField(choices=[('Aguarongo', 'Aguarongo'), ('Bulán (Jorge Andrade)', 'Bulán (Jorge Andrade)'), ('El Carmen del Pongo', 'El Carmen del Pongo'), ('El Sagrario', 'El Sagrario'), ('El Vecino', 'El Vecino'), ('Gil Ramírez Dávalos (Las Juntas)', 'Gil Ramírez Dávalos (Las Juntas)'), ('Huertas', 'Huertas'), ('Javier Loyola (Chuquipata)', 'Javier Loyola (Chuquipata)'), ('Luis Cordero Vega (Cuenca)', 'Luis Cordero Vega (Cuenca)'), ('Monay', 'Monay'), ('Octavio Cordero Palacios (Santa Rosa)', 'Octavio Cordero Palacios (Santa Rosa)'), ('Paccha', 'Paccha'), ('Quingeo', 'Quingeo'), ('Ricaurte', 'Ricaurte'), ('San Blas', 'San Blas'), ('San Joaquín', 'San Joaquín'), ('San José de Raranga', 'San José de Raranga'), ('San Roque', 'San Roque'), ('Santiago de Mendez', 'Santiago de Mendez'), ('Sayausí', 'Sayausí'), ('Sinincay', 'Sinincay'), ('Tarqui', 'Tarqui'), ('Turi', 'Turi'), ('Valle', 'Valle'), ('Victoria del Portete (Irquis)', 'Victoria del Portete (Irquis)'), ('Zhucay', 'Zhucay')], max_length=200, null=True)),
                ('parroquia2', models.CharField(choices=[('Guaranda', (('Guaranda', 'Guaranda'), ('Facundo Vela', 'Facundo Vela'), ('Julio E. Moreno', 'Julio E. Moreno'), ('Salinas', 'Salinas'))), ('Caluma', (('Caluma', 'Caluma'), ('La Victoria', 'La Victoria'), ('San Luis de Pambil', 'San Luis de Pambil'))), ('Chillanes', (('Chillanes', 'Chillanes'), ('San José del Tambo', 'San José del Tambo')))], max_length=200, null=True)),
                ('parroquia3', models.CharField(choices=[('Azogues', 'Azogues'), ('Biblián', 'Biblián'), ('Cañar', 'Cañar'), ('Déleg', 'Déleg'), ('El Tambo', 'El Tambo'), ('La Troncal', 'La Troncal'), ('Suscal', 'Suscal')], max_length=200, null=True)),
                ('parroquia4', models.CharField(choices=[('Tulcán', (('González Suárez', 'González Suárez'), ('Tufiño', 'Tufiño'))), ('Bolívar', (('Bolívar', 'Bolívar'), ('García Moreno', 'García Moreno'))), ('Espejo', (('El Ángel', 'El Ángel'), ('El Goaltal', 'El Goaltal')))], max_length=200, null=True)),
                ('parroquia5', models.CharField(choices=[('Riobamba', (('Riobamba', 'Riobamba'), ('Lizarzaburu', 'Lizarzaburu'), ('Licán', 'Licán'))), ('Alausí', (('Alausí', 'Alausí'), ('Achupallas', 'Achupallas')))], max_length=200, null=True)),
                ('parroquia6', models.CharField(choices=[('Latacunga', (('La Matriz', 'La Matriz'), ('Eloy Alfaro (San Felipe)', 'Eloy Alfaro (San Felipe)'), ('Ignacio Flores (Parque La Libertad)', 'Ignacio Flores (Parque La Libertad)'))), ('Salcedo', (('San Miguel', 'San Miguel'), ('Antonio José Holguín (Santa Lucía)', 'Antonio José Holguín (Santa Lucía)'))), ('Pujilí', (('San Francisco de Pujilí', 'San Francisco de Pujilí'), ('Alaques (Alaquez)', 'Alaques (Alaquez)')))], max_length=200, null=True)),
                ('parroquia7', models.CharField(choices=[('Atacames', 'Atacames'), ('La Unión', 'La Unión'), ('Limones', 'Limones'), ('Río Verde', 'Río Verde'), ('Tonsupa', 'Tonsupa')], max_length=200, null=True)),
                ('parroquia8', models.CharField(choices=[('Puerto Ayora', 'Puerto Ayora'), ('Puerto Baquerizo Moreno', 'Puerto Baquerizo Moreno')], max_length=200, null=True)),
                ('parroquia9', models.CharField(choices=[('Ibarra', (('Caranqui', 'Caranqui'), ('La Dolorosa del Priorato', 'La Dolorosa del Priorato'), ('San Antonio de Ibarra', 'San Antonio de Ibarra'), ('San Francisco de Ibarra', 'San Francisco de Ibarra'), ('Sagrario', 'Sagrario'))), ('Otavalo', (('Dr. Miguel Egas Cabezas', 'Dr. Miguel Egas Cabezas'), ('Cotacachi', 'Cotacachi'), ('Otavalo', 'Otavalo'), ('San José de Quichinche', 'San José de Quichinche'), ('San Juan de Ilumán', 'San Juan de Ilumán'), ('San Pablo', 'San Pablo')))], max_length=200, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('gero_ref', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='autoidenty_etnica',
            field=models.CharField(choices=[('Indígena', 'Indígena'), ('Afroecuatoriano', 'Afroecuatoriano'), ('Montubio', 'Montubio'), ('Mestizo/a', 'Mestizo/a'), ('Blanco/a', 'Blanco/a'), ('Otro/a', 'Otro/a')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dactilar',
            field=models.CharField(max_length=9, null=True, verbose_name='Código Dactilar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Indígena'), ('Mujer', 'Afroecuatoriano'), ('No binario', 'Montubio'), ('Género fluido', 'Género fluido'), ('Bigénero', 'Bigénero'), ('Transexual', 'Transexual'), ('Andrógino', 'Andrógino')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nacionalidad',
            field=models.CharField(max_length=125, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero_cedula',
            field=models.CharField(max_length=10, null=True, verbose_name='Número de cedula'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seudonimo',
            field=models.CharField(max_length=125, null=True, verbose_name='Seudónimo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
