# Generated by Django 4.2.6 on 2024-02-23 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_natural_profile_autoidenty_etnica_profile_dactilar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='natural',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='autoidenty_etnica',
            field=models.CharField(choices=[('Indígena', 'Indígena'), ('Afroecuatoriano', 'Afroecuatoriano'), ('Montubio', 'Montubio'), ('Mestizo/a', 'Mestizo/a'), ('Blanco/a', 'Blanco/a'), ('Otro/a', 'Otro/a')], max_length=200, null=True, verbose_name='Autoidentificación Etnica'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No binario', 'Montubio'), ('Género fluido', 'Género fluido'), ('Bigénero', 'Bigénero'), ('Transexual', 'Transexual'), ('Andrógino', 'Andrógino')], max_length=200, null=True, verbose_name='Autoidentificación Género'),
        ),
    ]
