# Generated by Django 4.2.6 on 2024-03-14 14:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_postulantes_lineas_fomentos_agregar_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantes_lineas_fomentos',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Escriba un obtivo principal del proyecto (el objetivo resume los resultados)'),
        ),
        migrations.AlterField(
            model_name='postulantes_lineas_fomentos',
            name='agregar_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Agregar nombre completo de participante de su proyecto'),
        ),
    ]
