# Generated by Django 4.2.6 on 2024-03-15 12:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_postulantes_lineas_fomentos_resumen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantes_lineas_fomentos',
            name='objetivo',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Escriba un obtivo principal del proyecto (el objetivo resume los resultados)'),
        ),
        migrations.AlterField(
            model_name='postulantes_lineas_fomentos',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Escriba un breve resumen de su proyecto y verifique si responde las siguientes interrogantes: ¿Cuál es el contexto del proyecto? ¿Quién es el público objetivo? ¿Cómo se va a desarrollar?'),
        ),
    ]
