# Generated by Django 4.2.6 on 2024-02-23 02:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_natural_user_alter_profile_autoidenty_etnica_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='natural',
            new_name='contacto',
        ),
    ]
