# Generated by Django 4.2.6 on 2024-02-23 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_alter_contacto_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.IntegerField(blank=True, null=True, verbose_name='¿Usted dispone de R.U.C?')),
                ('natu_juri', models.CharField(choices=[('Natural', 'Natural'), ('Jurídico', 'Jurídico')], max_length=200, null=True, verbose_name='¿En que estado legal desea realizar su registro?')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
