# Generated by Django 4.2.6 on 2024-02-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal',
            name='lucro_jury',
            field=models.CharField(choices=[('ASOCIACIONES SIN ÁNIMO DE LUCRO', 'ASOCIACIONES SIN ÁNIMO DE LUCRO'), ('ASOCIACIÓN DE CUENTAS DE PARTICIPACIÓN', 'ASOCIACIÓN DE CUENTAS DE PARTICIPACIÓN'), ('COMPAÑÍA LIMITADA CÍA. LTDA.', 'COMPAÑÍA LIMITADA CÍA. LTDA.'), ('EMPRESARIO INDIVIDUAL', 'EMPRESARIO INDIVIDUAL'), ('SOCIEDAD ANÓNIMA S.A.', 'SOCIEDAD ANÓNIMA S.A.'), ('SOCIEDAD DE ACCIONES SIMPLIFICADA S.A.S', 'SOCIEDAD DE ACCIONES SIMPLIFICADA S.A.S'), ('SOCIEDAD COLECTIVA', 'SOCIEDAD COLECTIVA.'), ('SOCIEDAD COMANDATARIA', 'SOCIEDAD COMANDATARIA'), ('SOCIEDAD COOPERATIVA', 'SOCIEDAD COOPERATIVA'), ('SOCIEDAD LIMITADA S.L.', 'SOCIEDAD LIMITADA S.L.')], max_length=200, null=True, verbose_name='Tipo de personería jurídica'),
        ),
        migrations.AddField(
            model_name='legal',
            name='tipo_jury',
            field=models.CharField(choices=[('ASOCIACIONES SIN ÁNIMO DE LUCRO', 'ASOCIACIONES SIN ÁNIMO DE LUCRO'), ('ASOCIACIÓN DE CUENTAS DE PARTICIPACIÓN', 'ASOCIACIÓN DE CUENTAS DE PARTICIPACIÓN'), ('COMPAÑÍA LIMITADA CÍA. LTDA.', 'COMPAÑÍA LIMITADA CÍA. LTDA.'), ('EMPRESARIO INDIVIDUAL', 'EMPRESARIO INDIVIDUAL'), ('SOCIEDAD ANÓNIMA S.A.', 'SOCIEDAD ANÓNIMA S.A.'), ('SOCIEDAD DE ACCIONES SIMPLIFICADA S.A.S', 'SOCIEDAD DE ACCIONES SIMPLIFICADA S.A.S'), ('SOCIEDAD COLECTIVA', 'SOCIEDAD COLECTIVA.'), ('SOCIEDAD COMANDATARIA', 'SOCIEDAD COMANDATARIA'), ('SOCIEDAD COOPERATIVA', 'SOCIEDAD COOPERATIVA'), ('SOCIEDAD LIMITADA S.L.', 'SOCIEDAD LIMITADA S.L.')], max_length=200, null=True, verbose_name='Tipo de personería jurídica'),
        ),
    ]
