# Generated by Django 4.2.6 on 2024-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_activity_legal_activity_jury_legal_autoidenty_etnica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='lucro_jury',
            field=models.CharField(max_length=200, null=True, verbose_name='¿ La personería jurídica tiene fines de lucro ?a'),
        ),
    ]
