# Generated by Django 4.2.6 on 2024-02-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_legal_lucro_jury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='lucro_jury',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=200, null=True, verbose_name='¿ La personería jurídica tiene fines de lucro ?a'),
        ),
    ]
