# Generated by Django 4.2.6 on 2024-02-28 04:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_alter_activity_options_alter_contacto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField(verbose_name='Escriba los términos y condiciones de manera declaratoria')),
                ('agree', models.BooleanField(default=False, verbose_name='Estoy deacuerdo con los términos y condiciones del contrato.')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validaciones de declaratorías del los postulantes',
                'verbose_name_plural': 'Validación de declaratoría del postulante',
            },
        ),
    ]
