# Generated by Django 4.2.6 on 2024-02-28 04:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='declaratoria',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
