# Generated by Django 4.2.6 on 2024-02-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_terms_declaratoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='declaratoria',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='terms',
        ),
    ]
