# Generated by Django 4.2.6 on 2024-02-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_terms_declaratoria_remove_terms_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='aprueba',
            field=models.BooleanField(default=False, verbose_name='El postulante aprobó la declaratoria'),
        ),
    ]
