# Generated by Django 4.2.6 on 2024-02-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_terms_aprueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='aprueba',
        ),
    ]
