version: "3.3"

services:
  qnd10app:
    image: smartquail/qnd10app:latest
    restart: unless-stopped
    environment:
      - PORT=9000
    env_file:
      - .env
    depends_on:
      - smartquaildb
    #  - redis
    #  - "worker"
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnd10:/qnd10app/qnd10app/staticfiles
      - static-data-qnd10:/qnd10app/qnd10app/media
   # command: sh -c "chmod +x /scripts/migrations.sh && sh /scripts/migrations.sh && sh /scripts/run.sh"
    networks: 
      - lansmartquail

  smartquaildb:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: always
    command: -p 5432
    ports:
      - "5432:5432"
    expose:
     - 5432
    volumes:
      - smartquaildb_data-qnode10:/var/lib/postgresql/data/
    networks: 
      - lansmartquail

  nginx:
    image: smartquail/qnd10_nginx:dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=80
    depends_on:
      - qnd10app
    ports:
      - 80:80
      - 443:443  
    volumes:
      - static-data-qnd10:/qnd10app/qnd10app/staticfiles
      - static-data-qnd10:/qnd10app/qnd10app/media
    networks: 
      - lansmartquail

 

volumes:
  static-data-qnd10:
  smartquaildb_data-qnode10:

networks: 
   lansmartquail:
       driver: bridge