# Generated by Django 4.2.6 on 2024-03-14 13:22

import announ.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='announ_linea_fomento_editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.FileField(blank=True, null=True, upload_to='documentos/portadas/')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre de convocatoria')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('overview', models.TextField(verbose_name='Descripción de Convocatoria')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('dias_diferencia', models.IntegerField(blank=True, default=0, null=True)),
                ('horas_diferencia', models.IntegerField(blank=True, default=0, null=True)),
                ('minutos_diferencia', models.IntegerField(blank=True, default=0, null=True)),
                ('segundos_diferencia', models.IntegerField(blank=True, default=0, null=True)),
                ('dias_diferencia_activacion', models.IntegerField(blank=True, default=0, null=True)),
                ('horas_diferencia_activacion', models.IntegerField(blank=True, default=0, null=True)),
                ('minutos_diferencia_activacion', models.IntegerField(blank=True, default=0, null=True)),
                ('segundos_diferencia_activacion', models.IntegerField(blank=True, default=0, null=True)),
                ('actividad', models.BooleanField(blank=True, null=True, verbose_name='Estado de la actividad de la convocatoría')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='bases_linea_fomento_editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', announ.fields.OrderField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='announ.announ_linea_fomento_editorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_linea_fomento_editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre de categoria')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Categorias_linea_fomento_editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre de categoria de la linea de fomento editorial')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='postulantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='¿Tiene un titulo?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulante_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='files')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='contenido_bases_linea_fomento_editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', announ.fields.OrderField(blank=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_bases', to='announ.bases_linea_fomento_editorial')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido de las bases')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announces', to='announ.categorias_linea_fomento_editorial', verbose_name='Categoria en la Línea de fomento editorial'),
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='fomento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fomento', to='announ.categoria_linea_fomento_editorial', verbose_name='Nombre de Línea de fomento'),
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announ_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='postulantes',
            field=models.ManyToManyField(blank=True, related_name='announces_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
