# Generated by Django 4.2.6 on 2024-03-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='portada',
            field=models.FileField(blank=True, null=True, upload_to='documentos/portadas/'),
        ),
    ]
