# Generated by Django 4.2.6 on 2024-03-15 12:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantes',
            name='agregar_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Agregar nombre completo de participante de su proyecto'),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad donde se desarolla el proyecto'),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='objetivo',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Escriba un obtivo principal del proyecto (el objetivo resume los resultados)'),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='provincia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Provincia donde se desarolla el proyecto'),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='resumen',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Escriba un breve resumen de su proyecto y verifique si responde las siguientes interrogantes: ¿Cuál es el contexto del proyecto? ¿Quién es el público objetivo? ¿Cómo se va a desarrollar?'),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='sector',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sector donde se desarolla el proyecto'),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del proyecto que desea postular'),
        ),
    ]
