# Generated by Django 4.2.6 on 2024-03-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announ_linea_fomento_editorial',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
