# Generated by Django 4.2.6 on 2024-03-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0003_announ_linea_fomento_editorial_dias_diferencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announ_linea_fomento_editorial',
            name='dias_diferencia',
        ),
        migrations.RemoveField(
            model_name='announ_linea_fomento_editorial',
            name='horas_diferencia',
        ),
        migrations.RemoveField(
            model_name='announ_linea_fomento_editorial',
            name='minutos_diferencia',
        ),
        migrations.RemoveField(
            model_name='announ_linea_fomento_editorial',
            name='segundos_diferencia',
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='horas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='minutos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='segundos',
            field=models.IntegerField(default=0),
        ),
    ]
