# Generated by Django 4.2.6 on 2024-03-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0004_remove_announ_linea_fomento_editorial_dias_diferencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announ_linea_fomento_editorial',
            old_name='dias',
            new_name='dias_diferencia',
        ),
        migrations.RenameField(
            model_name='announ_linea_fomento_editorial',
            old_name='horas',
            new_name='horas_diferencia',
        ),
        migrations.RenameField(
            model_name='announ_linea_fomento_editorial',
            old_name='minutos',
            new_name='minutos_diferencia',
        ),
        migrations.RemoveField(
            model_name='announ_linea_fomento_editorial',
            name='segundos',
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='segundos_diferencia',
            field=models.IntegerField(default=0),
        ),
    ]
