# Generated by Django 4.2.6 on 2024-03-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0005_rename_dias_announ_linea_fomento_editorial_dias_diferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
