# Generated by Django 4.2.6 on 2024-03-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0006_announ_linea_fomento_editorial_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='actividad',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado de la actividad de la convocatoría'),
        ),
    ]
