# Generated by Django 4.2.6 on 2024-03-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0008_alter_announ_linea_fomento_editorial_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announ_linea_fomento_editorial',
            name='actividad',
            field=models.BooleanField(blank=True, null=True, verbose_name='Estado de la actividad de la convocatoría'),
        ),
    ]
