# Generated by Django 4.2.6 on 2024-03-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0009_alter_announ_linea_fomento_editorial_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='dias_diferencia_activacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='horas_diferencia_activacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='minutos_diferencia_activacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announ_linea_fomento_editorial',
            name='segundos_diferencia_activacion',
            field=models.IntegerField(default=0),
        ),
    ]
