# Generated by Django 4.2.6 on 2024-03-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announ', '0010_announ_linea_fomento_editorial_dias_diferencia_activacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announ_linea_fomento_editorial',
            name='dias_diferencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='announ_linea_fomento_editorial',
            name='dias_diferencia_activacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='announ_linea_fomento_editorial',
            name='horas_diferencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='announ_linea_fomento_editorial',
            name='horas_diferencia_activacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='announ_linea_fomento_editorial',
            name='minutos_diferencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='announ_linea_fomento_editorial',
            name='minutos_diferencia_activacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='announ_linea_fomento_editorial',
            name='segundos_diferencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='announ_linea_fomento_editorial',
            name='segundos_diferencia_activacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
