# Generated by Django 4.2.6 on 2024-03-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fomento_Editorial', '0002_course_actividad_course_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created'], 'verbose_name': 'Convocatoria Editorial & Fomento', 'verbose_name_plural': 'Convocatorias Editorial & Fomento'},
        ),
        migrations.AddField(
            model_name='course',
            name='portada',
            field=models.FileField(blank=True, null=True, upload_to='documentos/portadas/'),
        ),
    ]
