# Generated by Django 4.2.6 on 2024-03-19 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fomento_Editorial', '0003_alter_course_options_course_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Escriba el nombre de la línea de fomento correspondiente')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Categorías de Fomento',
                'verbose_name_plural': 'Categoría de Fomento',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'Categorías de Convocatorias', 'verbose_name_plural': 'Categoría de Convocatoria'},
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Fomento_Editorial.subject', verbose_name='Categoría de convocatoria'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Escriba el nombre de la categoría de convocatoria correspondiente'),
        ),
        migrations.AddField(
            model_name='course',
            name='fomento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Fomento_Editorial.fomento', verbose_name='Línea de fomento'),
        ),
    ]
