# Generated by Django 4.2.6 on 2024-03-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fomento_Editorial', '0005_alter_course_fomento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='actividad',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Desea activar esta convocatoria ?'),
        ),
    ]
