# Generated by Django 4.2.6 on 2024-03-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fomento_Editorial', '0006_alter_course_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
