# Generated by Django 4.2.6 on 2024-03-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fomento_Editorial', '0008_alter_course_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
