# Generated by Django 4.2.11 on 2024-04-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_literaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portada/%Y/%m/%d/', verbose_name='Foto de portada de convocatoria'),
        ),
    ]
