# Generated by Django 4.2.11 on 2024-04-30 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editorial_literaria', '0002_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='postulante',
            field=models.ManyToManyField(blank=True, related_name='projects_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('postulante', models.ManyToManyField(blank=True, related_name='project_user_joined', to=settings.AUTH_USER_MODEL)),
                ('title', models.ManyToManyField(blank=True, related_name='project_title', to='editorial_literaria.proyectos')),
            ],
            options={
                'verbose_name_plural': 'Proyectos Postulados',
                'ordering': ['-created'],
            },
        ),
    ]
