# Generated by Django 4.2.12 on 2024-05-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_literaria', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
