# Generated by Django 4.2.11 on 2024-04-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_literaria', '0003_manual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manual',
            new_name='ManualCreateConvocatoria',
        ),
    ]
