# Generated by Django 4.2.11 on 2024-04-13 20:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_literaria', '0004_rename_manual_manualcreateconvocatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEditConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Crear Convocatoria', 'Crear Convocatoria'), ('Editar Convocatoria', 'Editar Convocatoria'), ('Mis Convocatorias', 'Mis Convocatorias'), ('inscripsion', 'inscripsion'), ('Mis Postulaciones', 'Mis Postulaciones'), ('Crear Proyecto', 'Crear Proyecto'), ('Editar Proyecto', 'Editar Proyecto'), ('Mis Proyectos', 'Mis Proyectos')], max_length=100, verbose_name='Selecione el tipo de manual')),
                ('titulo', models.CharField(max_length=100)),
                ('informacion_basica', ckeditor.fields.RichTextField()),
                ('bloque_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ManualMisConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Crear Convocatoria', 'Crear Convocatoria'), ('Editar Convocatoria', 'Editar Convocatoria'), ('Mis Convocatorias', 'Mis Convocatorias'), ('inscripsion', 'inscripsion'), ('Mis Postulaciones', 'Mis Postulaciones'), ('Crear Proyecto', 'Crear Proyecto'), ('Editar Proyecto', 'Editar Proyecto'), ('Mis Proyectos', 'Mis Proyectos')], max_length=100, verbose_name='Selecione el tipo de manual')),
                ('titulo', models.CharField(max_length=100)),
                ('informacion_basica', ckeditor.fields.RichTextField()),
                ('bloque_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
