# Generated by Django 4.2.11 on 2024-04-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_literaria', '0007_manualcrearproyecto_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcreateconvocatoria',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualcreateconvocatoria',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualcreateconvocatoria',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualcreateconvocatoria',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualcreateconvocatoria',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
    ]
