# Generated by Django 4.2.11 on 2024-04-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_literaria', '0008_alter_manualcreateconvocatoria_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcrearproyecto',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualcrearproyecto',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualcrearproyecto',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualcrearproyecto',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualcrearproyecto',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditconvocatoria',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditconvocatoria',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditconvocatoria',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditconvocatoria',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditconvocatoria',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditproyecto',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditproyecto',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditproyecto',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditproyecto',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualeditproyecto',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualinscripcion',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualinscripcion',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualinscripcion',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualinscripcion',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualinscripcion',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisconvocatoria',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisconvocatoria',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisconvocatoria',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisconvocatoria',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisconvocatoria',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmispostulaciones',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmispostulaciones',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmispostulaciones',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmispostulaciones',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmispostulaciones',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisproyectos',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisproyectos',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisproyectos',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisproyectos',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
        migrations.AlterField(
            model_name='manualmisproyectos',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/%Y/%m/%d/', verbose_name='Seleccione una imagen'),
        ),
    ]
