# Generated by Django 4.2.9 on 2024-02-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bases',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción de convocatoria'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='overview',
            field=models.TextField(verbose_name='Descripción de convocatoria'),
        ),
    ]
