# Generated by Django 4.2.6 on 2024-02-07 23:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_alter_bases_description_alter_convocatoria_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term1', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
