# Generated by Django 4.2.6 on 2024-02-08 00:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='term2',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term3',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term4',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term5',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term6',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term7',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
