# Generated by Django 4.2.12 on 2024-05-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_espacio_publico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento_30000',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AddField(
            model_name='evento_30000',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Evento_url'),
        ),
    ]
