# Generated by Django 4.2.12 on 2024-05-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_espacio_publico', '0002_rename_usuario_evento_30000_user_evento_30000_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento_30000',
            name='url',
        ),
        migrations.AddField(
            model_name='subject',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Evento_url'),
        ),
    ]
