# Generated by Django 4.2.12 on 2024-05-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_espacio_publico', '0003_remove_evento_30000_url_subject_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento_10000',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='evento_20000',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='evento_5000',
            old_name='usuario',
            new_name='user',
        ),
    ]
