# Generated by Django 4.2.13 on 2024-05-31 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_legal_lugar_residencia_and_more'),
        ('actividades_espacio_publico', '0006_alter_evento_30000_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento_30000',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_30000', to='usuarios.profile'),
        ),
    ]
