# Generated by Django 4.2.13 on 2024-05-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_espacio_publico', '0007_evento_30000_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento_30000',
            name='profile',
        ),
    ]
